- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
#once the directory is removed above, we need to create a new one below
- name: create HTTP Document directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download front end App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: true

- name: Copy Roboshop configuration file to Nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
