- name: Configure NodeJS repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Remove old content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download Catalogue App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install Nodejs dependencies
  ansible.builtin.npm:
    path: /app
    state: latest

- name: Copy systemD file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: true

- name: Copy module of mongod
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongoshell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.mithundevops.online
    file: "/app/schema/catalogue.js"
    idempotent: yes