- name: Install goalng
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Add application user
  ansible.builtin.include_tasks:
    file: app-preq.yaml

- name: create app Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download {{component}} App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes

- name: Go Build
  ansible.builtin.shell: go mod init dispatch; go get; go build
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yaml"