- name: Copy module of mongod
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongoshell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.mithundevops.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes
    import_tasks: "{{schema_type}}-schema.yaml"