- name: Install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Add application user
  ansible.builtin.include_tasks:
   name: app-preq.yaml

- name: Download Python Dependencies
  ansible.builtin.pip:
   requirements: /app/requirements.txt
   executable: pip3.6

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yaml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{Schema_type}}-schema.yaml"
  when: schema_load
